export const SET_PRODUCT_LIST="SET_PRODUCT_LIST";
export const TOGGLE_FIRST_MODAL="TOGGLE_FIRST_MODAL";
export const TOGGLE_REMOVE_MODAL="TOGGLE_REMOVE_MODAL";
export const SET_FAVOURITES_ID="SET_FAVOURITES_ID";
